
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 02 13:24:40 CEST 2015
//----------------------------------------------------

package oblig1NF;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RBRACK = 5;
  public static final int LT = 25;
  public static final int CLASS = 3;
  public static final int EXPOP = 28;
  public static final int PLUS = 23;
  public static final int INT = 17;
  public static final int EQUAL = 22;
  public static final int THEN = 13;
  public static final int SEMI = 8;
  public static final int FSTOP = 27;
  public static final int LBRACK = 4;
  public static final int NOT = 14;
  public static final int RETURN = 9;
  public static final int REF = 20;
  public static final int IF = 12;
  public static final int GT = 24;
  public static final int COLON = 15;
  public static final int ID = 29;
  public static final int PROGRAM = 2;
  public static final int STRING_LITERAL = 30;
  public static final int STRING = 18;
  public static final int COMMA = 26;
  public static final int FLOAT = 16;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PROC = 21;
  public static final int NEW = 11;
  public static final int BOOL = 19;
  public static final int INTEGER = 31;
  public static final int RPAR = 7;
  public static final int FLOAT_LITERAL = 32;
  public static final int VAR = 10;
  public static final int LPAR = 6;
}

